[2024-12-15T03:22:23.613+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_price_volume_etl.retry_missing_tickers manual__2024-12-15T03:21:05.973178+00:00 [queued]>
[2024-12-15T03:22:23.617+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_price_volume_etl.retry_missing_tickers manual__2024-12-15T03:21:05.973178+00:00 [queued]>
[2024-12-15T03:22:23.617+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-12-15T03:22:23.624+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retry_missing_tickers> on 2024-12-15 03:21:05.973178+00:00
[2024-12-15T03:22:23.628+0000] {standard_task_runner.py:57} INFO - Started process 946 to run task
[2024-12-15T03:22:23.630+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_price_volume_etl', 'retry_missing_tickers', 'manual__2024-12-15T03:21:05.973178+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp6iiokivt']
[2024-12-15T03:22:23.631+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask retry_missing_tickers
[2024-12-15T03:22:23.651+0000] {task_command.py:416} INFO - Running <TaskInstance: daily_price_volume_etl.retry_missing_tickers manual__2024-12-15T03:21:05.973178+00:00 [running]> on host 57c3a4cf23dc
[2024-12-15T03:22:23.694+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_price_volume_etl' AIRFLOW_CTX_TASK_ID='retry_missing_tickers' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T03:21:05.973178+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T03:21:05.973178+00:00'
[2024-12-15T03:22:34.446+0000] {multi.py:176} ERROR - 
2 Failed downloads:
[2024-12-15T03:22:34.447+0000] {multi.py:189} ERROR - ['[', ']']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
[2024-12-15T03:22:34.452+0000] {etl.py:68} ERROR - No data downloaded
[2024-12-15T03:22:34.453+0000] {etl.py:112} ERROR - Missing column: Ticker
[2024-12-15T03:22:34.454+0000] {etl.py:224} ERROR - ETL Transformation failed: Validation Error
[2024-12-15T03:22:34.454+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/src/etl.py", line 199, in transform_pipeline
    raise ValueError(f"Validation Error")
ValueError: Validation Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/etl.py", line 371, in run_daily_pipeline
    df,missing_tickers =  transform_pipeline(df,all_tickers = tickers)
  File "/opt/airflow/dags/src/etl.py", line 225, in transform_pipeline
    raise ValueError("Transformation failed")
ValueError: Transformation failed
[2024-12-15T03:22:34.461+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_price_volume_etl, task_id=retry_missing_tickers, execution_date=20241215T032105, start_date=20241215T032223, end_date=20241215T032234
[2024-12-15T03:22:34.470+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 55 for task retry_missing_tickers (Transformation failed; 946)
[2024-12-15T03:22:34.505+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-15T03:22:34.514+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
