[2024-12-15T15:44:16.544-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_price_volume_etl.get_missing_tikers manual__2024-12-15T20:23:50.674160+00:00 [queued]>
[2024-12-15T15:44:16.551-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_price_volume_etl.get_missing_tikers manual__2024-12-15T20:23:50.674160+00:00 [queued]>
[2024-12-15T15:44:16.551-0500] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2024-12-15T15:44:16.560-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_missing_tikers> on 2024-12-15 20:23:50.674160+00:00
[2024-12-15T15:44:16.563-0500] {standard_task_runner.py:57} INFO - Started process 680 to run task
[2024-12-15T15:44:16.566-0500] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_price_volume_etl', 'get_missing_tikers', 'manual__2024-12-15T20:23:50.674160+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmphl35g36a']
[2024-12-15T15:44:16.568-0500] {standard_task_runner.py:85} INFO - Job 428: Subtask get_missing_tikers
[2024-12-15T15:44:16.614-0500] {task_command.py:416} INFO - Running <TaskInstance: daily_price_volume_etl.get_missing_tikers manual__2024-12-15T20:23:50.674160+00:00 [running]> on host 1e0c6de054af
[2024-12-15T15:44:16.756-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_price_volume_etl' AIRFLOW_CTX_TASK_ID='get_missing_tikers' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T20:23:50.674160+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T20:23:50.674160+00:00'
[2024-12-15T15:44:16.763-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/etl.py", line 411, in get_missing_tikers
    raw_df = pd.read_csv(raw_data_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/src/../../landing_zone/daily_price_volume_etl/fetch_raw_data/2024-12-15T20:23:50.674160+00:00raw_data.csv'
[2024-12-15T15:44:16.768-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=daily_price_volume_etl, task_id=get_missing_tikers, execution_date=20241215T202350, start_date=20241215T204416, end_date=20241215T204416
[2024-12-15T15:44:16.774-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 428 for task get_missing_tikers ([Errno 2] No such file or directory: '/opt/airflow/dags/src/../../landing_zone/daily_price_volume_etl/fetch_raw_data/2024-12-15T20:23:50.674160+00:00raw_data.csv'; 680)
[2024-12-15T15:44:16.800-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
