[2024-12-15T00:39:05.548-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_price_volume_etl.retry_missing_tickers manual__2024-12-15T05:23:58.814570+00:00 [queued]>
[2024-12-15T00:39:05.554-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_price_volume_etl.retry_missing_tickers manual__2024-12-15T05:23:58.814570+00:00 [queued]>
[2024-12-15T00:39:05.555-0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2024-12-15T00:39:05.563-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retry_missing_tickers> on 2024-12-15 05:23:58.814570+00:00
[2024-12-15T00:39:05.565-0500] {standard_task_runner.py:57} INFO - Started process 67 to run task
[2024-12-15T00:39:05.568-0500] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_price_volume_etl', 'retry_missing_tickers', 'manual__2024-12-15T05:23:58.814570+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp9ykzb0sh']
[2024-12-15T00:39:05.570-0500] {standard_task_runner.py:85} INFO - Job 324: Subtask retry_missing_tickers
[2024-12-15T00:39:05.594-0500] {task_command.py:416} INFO - Running <TaskInstance: daily_price_volume_etl.retry_missing_tickers manual__2024-12-15T05:23:58.814570+00:00 [running]> on host d5d7f84d2f8f
[2024-12-15T00:39:05.634-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_price_volume_etl' AIRFLOW_CTX_TASK_ID='retry_missing_tickers' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T05:23:58.814570+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T05:23:58.814570+00:00'
[2024-12-15T00:39:05.636-0500] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-12-15T00:39:05.636-0500] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-12-15T00:39:05.637-0500] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-12-15T00:39:19.667-0500] {base.py:128} ERROR - Failed to get ticker 'O' reason: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Read timed out. (read timeout=10)
[2024-12-15T00:39:19.680-0500] {multi.py:176} ERROR - 
2 Failed downloads:
[2024-12-15T00:39:19.682-0500] {multi.py:189} ERROR - ['N']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2023-12-10 -> 2024-12-10)')
[2024-12-15T00:39:19.682-0500] {multi.py:189} ERROR - ['O']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
[2024-12-15T00:39:19.707-0500] {etl.py:136} INFO - All columns validated successfully.
[2024-12-15T00:39:19.709-0500] {logging_mixin.py:154} INFO - Number of records with out-of-range AdjClose: 0
[2024-12-15T00:39:19.710-0500] {logging_mixin.py:154} INFO - Number of records with out-of-range Date: 0
[2024-12-15T00:39:19.714-0500] {etl.py:189} INFO - Dropped 1 rows with missing values in ['ticker', 'date', 'adj_close', 'close', 'ret_1d'].
[2024-12-15T00:39:19.715-0500] {etl.py:222} WARNING - Missing tickers: ['N', 'e', 'n', 'o']
[2024-12-15T00:39:19.715-0500] {etl.py:223} INFO - Transformation pipeline completed successfully.
[2024-12-15T00:39:19.742-0500] {logging_mixin.py:154} INFO - Inserted 250 rows out of 250 records
[2024-12-15T00:39:19.743-0500] {python.py:194} INFO - Done. Returned value was: None
[2024-12-15T00:39:19.747-0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=daily_price_volume_etl, task_id=retry_missing_tickers, execution_date=20241215T052358, start_date=20241215T053905, end_date=20241215T053919
[2024-12-15T00:39:19.778-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-12-15T00:39:19.785-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
