[2024-12-15T14:58:29.458-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_price_volume_etl_2.run_initial_pipeline scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T14:58:29.464-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_price_volume_etl_2.run_initial_pipeline scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T14:58:29.464-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-12-15T14:58:29.470-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_initial_pipeline> on 2024-12-14 00:00:00+00:00
[2024-12-15T14:58:29.472-0500] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2024-12-15T14:58:29.475-0500] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_price_volume_etl_2', 'run_initial_pipeline', 'scheduled__2024-12-14T00:00:00+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpnmdwdiml']
[2024-12-15T14:58:29.477-0500] {standard_task_runner.py:85} INFO - Job 334: Subtask run_initial_pipeline
[2024-12-15T14:58:29.501-0500] {task_command.py:416} INFO - Running <TaskInstance: daily_price_volume_etl_2.run_initial_pipeline scheduled__2024-12-14T00:00:00+00:00 [running]> on host 5299d9743533
[2024-12-15T14:58:29.597-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_price_volume_etl_2' AIRFLOW_CTX_TASK_ID='run_initial_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T00:00:00+00:00'
[2024-12-15T14:58:29.600-0500] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-12-15T14:58:29.600-0500] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-12-15T14:58:29.600-0500] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-12-15T14:58:29.601-0500] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-12-15T14:59:21.169-0500] {base.py:128} ERROR - Failed to get ticker 'GM' reason: Expecting value: line 1 column 1 (char 0)
[2024-12-15T14:59:21.170-0500] {base.py:128} ERROR - Failed to get ticker 'GPC' reason: Expecting value: line 1 column 1 (char 0)
[2024-12-15T14:59:21.171-0500] {base.py:128} ERROR - Failed to get ticker 'FICO' reason: Expecting value: line 1 column 1 (char 0)
[2024-12-15T14:59:41.162-0500] {multi.py:176} ERROR - 
3 Failed downloads:
[2024-12-15T14:59:41.163-0500] {multi.py:189} ERROR - ['GM', 'GPC', 'FICO']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
[2024-12-15T14:59:41.554-0500] {etl.py:146} INFO - All columns validated successfully.
[2024-12-15T14:59:41.600-0500] {logging_mixin.py:154} INFO - Number of records with out-of-range AdjClose: 0
[2024-12-15T14:59:41.612-0500] {logging_mixin.py:154} INFO - Number of records with out-of-range Date: 0
[2024-12-15T14:59:41.699-0500] {etl.py:192} INFO - Dropped 500 rows with missing values in ['ticker', 'date', 'adj_close', 'close', 'ret_1d'].
[2024-12-15T14:59:41.700-0500] {etl.py:223} INFO - Transformation pipeline completed successfully.
[2024-12-15T14:59:42.910-0500] {etl.py:309} INFO - Inserted 12500 rows out of 12500 records
[2024-12-15T14:59:43.302-0500] {etl.py:309} INFO - Inserted 12500 rows out of 12500 records
[2024-12-15T14:59:43.382-0500] {etl.py:309} INFO - Inserted 12500 rows out of 12500 records
[2024-12-15T14:59:43.394-0500] {etl.py:309} INFO - Inserted 12489 rows out of 12489 records
[2024-12-15T14:59:43.496-0500] {etl.py:309} INFO - Inserted 12500 rows out of 12500 records
[2024-12-15T14:59:43.501-0500] {etl.py:309} INFO - Inserted 12425 rows out of 12425 records
[2024-12-15T14:59:43.504-0500] {etl.py:309} INFO - Inserted 12500 rows out of 12500 records
[2024-12-15T14:59:43.544-0500] {etl.py:309} INFO - Inserted 12500 rows out of 12500 records
[2024-12-15T14:59:43.561-0500] {etl.py:309} INFO - Inserted 12500 rows out of 12500 records
[2024-12-15T14:59:43.568-0500] {etl.py:309} INFO - Inserted 12283 rows out of 12283 records
[2024-12-15T14:59:43.575-0500] {python.py:194} INFO - Done. Returned value was: None
[2024-12-15T14:59:43.580-0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=daily_price_volume_etl_2, task_id=run_initial_pipeline, execution_date=20241214T000000, start_date=20241215T195829, end_date=20241215T195943
[2024-12-15T14:59:43.629-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-12-15T14:59:43.637-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
