[2024-12-15T02:58:17.011+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_price_volume_etl.run_initial_pipeline manual__2024-12-15T02:18:12.735319+00:00 [queued]>
[2024-12-15T02:58:17.017+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_price_volume_etl.run_initial_pipeline manual__2024-12-15T02:18:12.735319+00:00 [queued]>
[2024-12-15T02:58:17.017+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-12-15T02:58:17.027+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_initial_pipeline> on 2024-12-15 02:18:12.735319+00:00
[2024-12-15T02:58:17.030+0000] {standard_task_runner.py:57} INFO - Started process 89 to run task
[2024-12-15T02:58:17.032+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_price_volume_etl', 'run_initial_pipeline', 'manual__2024-12-15T02:18:12.735319+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp3948nd5g']
[2024-12-15T02:58:17.033+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask run_initial_pipeline
[2024-12-15T02:58:17.058+0000] {task_command.py:416} INFO - Running <TaskInstance: daily_price_volume_etl.run_initial_pipeline manual__2024-12-15T02:18:12.735319+00:00 [running]> on host d8de91b8ea1a
[2024-12-15T02:58:17.164+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_price_volume_etl' AIRFLOW_CTX_TASK_ID='run_initial_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T02:18:12.735319+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T02:18:12.735319+00:00'
[2024-12-15T02:58:17.167+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-12-15T02:58:17.168+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-12-15T02:58:17.167+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
